// <auto-generated />
using System;
using CurveAnalyzer.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CurveAnalyzer.Infrastructure.Migrations
{
    [DbContext(typeof(MoexContext))]
    [Migration("20260508124217_AddOfzMarketIndexPoints")]
    partial class AddOfzMarketIndexPoints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("CurveAnalyzer.Core.CbrKeyRate", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LoadedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Rate")
                        .HasColumnType("REAL");

                    b.HasKey("Date");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_CbrKeyRates_Date");

                    b.ToTable("CbrKeyRates");
                });

            modelBuilder.Entity("CurveAnalyzer.Core.OfzActivityLoadState", b =>
                {
                    b.Property<string>("BoardId")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TradeDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsProvisional")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LoadedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RowsLoaded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("BoardId", "TradeDate");

                    b.HasIndex("TradeDate")
                        .HasDatabaseName("IX_OfzActivityLoadStates_TradeDate");

                    b.ToTable("OfzActivityLoadStates");
                });

            modelBuilder.Entity("CurveAnalyzer.Core.OfzDailyTrade", b =>
                {
                    b.Property<string>("BoardId")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TradeDate")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Bid")
                        .HasColumnType("REAL");

                    b.Property<double?>("ClosePrice")
                        .HasColumnType("REAL");

                    b.Property<double?>("Duration")
                        .HasColumnType("REAL");

                    b.Property<double?>("HighBid")
                        .HasColumnType("REAL");

                    b.Property<double?>("HighPrice")
                        .HasColumnType("REAL");

                    b.Property<double?>("ImpliedCbrRate")
                        .HasColumnType("REAL");

                    b.Property<double?>("ImpliedFloatingRate")
                        .HasColumnType("REAL");

                    b.Property<double?>("ImpliedInflation")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("LoadedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("LowOffer")
                        .HasColumnType("REAL");

                    b.Property<double?>("LowPrice")
                        .HasColumnType("REAL");

                    b.Property<int?>("NumTrades")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Offer")
                        .HasColumnType("REAL");

                    b.Property<double?>("OpenPrice")
                        .HasColumnType("REAL");

                    b.Property<double?>("Spread")
                        .HasColumnType("REAL");

                    b.Property<double?>("Value")
                        .HasColumnType("REAL");

                    b.Property<double?>("Volume")
                        .HasColumnType("REAL");

                    b.Property<double?>("WeightedAveragePrice")
                        .HasColumnType("REAL");

                    b.Property<double?>("YieldAtWeightedAveragePrice")
                        .HasColumnType("REAL");

                    b.Property<double?>("YieldClose")
                        .HasColumnType("REAL");

                    b.Property<double?>("ZSpread")
                        .HasColumnType("REAL");

                    b.Property<double?>("ZSpreadAtWeightedAveragePrice")
                        .HasColumnType("REAL");

                    b.HasKey("BoardId", "SecId", "TradeDate");

                    b.HasIndex("TradeDate")
                        .HasDatabaseName("IX_OfzDailyTrades_TradeDate");

                    b.HasIndex("SecId", "TradeDate")
                        .HasDatabaseName("IX_OfzDailyTrades_SecId_TradeDate");

                    b.HasIndex("TradeDate", "Duration")
                        .HasDatabaseName("IX_OfzDailyTrades_TradeDate_Duration");

                    b.ToTable("OfzDailyTrades");
                });

            modelBuilder.Entity("CurveAnalyzer.Core.OfzIssue", b =>
                {
                    b.Property<string>("SecId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("BondSubType")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("BondType")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClassificationEvidence")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClassificationLoadedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClassificationReliability")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClassificationSource")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<double?>("CouponPercent")
                        .HasColumnType("REAL");

                    b.Property<int?>("CouponPeriod")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("CouponValue")
                        .HasColumnType("REAL");

                    b.Property<string>("CurrencyId")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("FaceUnit")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<double?>("FaceValue")
                        .HasColumnType("REAL");

                    b.Property<double?>("InitialFaceValue")
                        .HasColumnType("REAL");

                    b.Property<bool?>("IsAmortizing")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsIndexedNominal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Isin")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("IssueName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<double?>("IssueSize")
                        .HasColumnType("REAL");

                    b.Property<double?>("IssueSizePlaced")
                        .HasColumnType("REAL");

                    b.Property<int?>("ListLevel")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("MatDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("MetadataLoadedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextCouponDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NominalCurrency")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedCouponType")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedTypeMarker")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("SecId");

                    b.ToTable("OfzIssues");
                });

            modelBuilder.Entity("CurveAnalyzer.Core.OfzLiquiditySnapshot", b =>
                {
                    b.Property<string>("BoardId")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TradeDate")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Bid")
                        .HasColumnType("REAL");

                    b.Property<double?>("BidDepth")
                        .HasColumnType("REAL");

                    b.Property<double?>("BidDepthTotal")
                        .HasColumnType("REAL");

                    b.Property<double?>("Duration")
                        .HasColumnType("REAL");

                    b.Property<double?>("DurationAtWeightedAveragePrice")
                        .HasColumnType("REAL");

                    b.Property<double?>("EffectiveYield")
                        .HasColumnType("REAL");

                    b.Property<double?>("EffectiveYieldAtWeightedAveragePrice")
                        .HasColumnType("REAL");

                    b.Property<double?>("GSpreadBp")
                        .HasColumnType("REAL");

                    b.Property<double?>("ImpliedCbrRate")
                        .HasColumnType("REAL");

                    b.Property<double?>("ImpliedFloatingRate")
                        .HasColumnType("REAL");

                    b.Property<double?>("ImpliedInflation")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsProvisional")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NumBids")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NumOffers")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NumTrades")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ObservedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Offer")
                        .HasColumnType("REAL");

                    b.Property<double?>("OfferDepth")
                        .HasColumnType("REAL");

                    b.Property<double?>("OfferDepthTotal")
                        .HasColumnType("REAL");

                    b.Property<double?>("Spread")
                        .HasColumnType("REAL");

                    b.Property<double?>("ValueToday")
                        .HasColumnType("REAL");

                    b.Property<double?>("VolumeToday")
                        .HasColumnType("REAL");

                    b.Property<double?>("ZSpread")
                        .HasColumnType("REAL");

                    b.Property<double?>("ZSpreadAtWeightedAveragePrice")
                        .HasColumnType("REAL");

                    b.Property<double?>("ZSpreadBp")
                        .HasColumnType("REAL");

                    b.HasKey("BoardId", "SecId", "TradeDate");

                    b.HasIndex("TradeDate")
                        .HasDatabaseName("IX_OfzLiquiditySnapshots_TradeDate");

                    b.HasIndex("SecId", "TradeDate")
                        .HasDatabaseName("IX_OfzLiquiditySnapshots_SecId_TradeDate");

                    b.ToTable("OfzLiquiditySnapshots");
                });

            modelBuilder.Entity("CurveAnalyzer.Core.OfzMarketIndexPoint", b =>
                {
                    b.Property<string>("SecId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TradeDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceKind")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Close")
                        .HasColumnType("REAL");

                    b.Property<string>("CurrencyId")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Duration")
                        .HasColumnType("REAL");

                    b.Property<double?>("High")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsProvisional")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LoadedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Low")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ObservedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Open")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("RecalcDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TradeSessionDate")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Value")
                        .HasColumnType("REAL");

                    b.Property<double?>("Yield")
                        .HasColumnType("REAL");

                    b.HasKey("SecId", "TradeDate", "SourceKind");

                    b.HasIndex("TradeDate")
                        .HasDatabaseName("IX_OfzMarketIndexPoints_TradeDate");

                    b.HasIndex("SecId", "TradeDate")
                        .HasDatabaseName("IX_OfzMarketIndexPoints_SecId_TradeDate");

                    b.ToTable("OfzMarketIndexPoints");
                });

            modelBuilder.Entity("CurveAnalyzer.Core.Zcyc", b =>
                {
                    b.Property<long>("Num")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Period")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Tradedate")
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Num");

                    b.HasIndex("Period", "Tradedate")
                        .HasDatabaseName("IX_Zcycs_Period_Tradedate");

                    b.HasIndex("Tradedate", "Period")
                        .HasDatabaseName("IX_Zcycs_Tradedate_Period");

                    b.ToTable("Zcycs");
                });

            modelBuilder.Entity("CurveAnalyzer.Core.OfzDailyTrade", b =>
                {
                    b.HasOne("CurveAnalyzer.Core.OfzIssue", "Issue")
                        .WithMany()
                        .HasForeignKey("SecId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");
                });
#pragma warning restore 612, 618
        }
    }
}
