<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Diagnostics" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="LiveChartsCore.SkiaSharpView.WPF" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CurveAnalyzer.ApiServices\CurveAnalyzer.ApiServices.csproj" />
    <ProjectReference Include="..\CurveAnalyzer.Application\CurveAnalyzer.Application.csproj" />
    <ProjectReference Include="..\CurveAnalyzer.Infrastructure\CurveAnalyzer.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
